services:
  - type: web
    name: laravel-render-app
    env: docker
    plan: free
    dockerContext: .
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromService:
          name: laravel-db
          type: pserv
      - key: DB_DATABASE
        value: laravel
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: password

databases:
  - name: laravel-db
    databaseName: laravel
    user: root
