services:
  - type: web
    name: laravel-app
    env: docker
    dockerContext: .
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d1fm6hqli9vc739mrhh0-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: task_manager_db_d28i
      - key: DB_USERNAME
        value: task_manager_db_d28i_user
      - key: DB_PASSWORD
        value: o9VfWLd1qeupHRKZ531r3dIoTOsgtySw
